behaviors:
    kart:
        trainer_type: ppo
        hyperparameters:
            batch_size: 1024
            buffer_size: 10240
            learning_rate: 1.0e-4
            beta: 5.0e-3
            epsilon: 0.2
            lambd: 0.99
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
            vis_encode_type: simple
        max_steps: 5.0e10
        time_horizon: 64
        keep_checkpoints: 64
        summary_freq: 10000
        reward_signals:
            extrinsic:
                strength: 0.4
                gamma: 0.99
            gail:
                gamma: 0.99
                strength: 0.5
                demo_path: C:\Users\Vincent\Documents\Cours\GenieTI\\LOG725\\LOG725\Assets\Demonstrations\kart_demo_mountain.demo
        behavioral_cloning:
            demo_path: C:\Users\Vincent\Documents\Cours\GenieTI\\LOG725\\LOG725\Assets\Demonstrations\kart_demo_mountain.demo
            strength: 0.5
        max_steps: 1000000
